targets:
  $default:
    builders:
      # Serializer
      json_serializable:
        options:
          explicit_to_json: true
          # By deafult, field_rename: none, More options —
          # snake, kebab, pascal, etc. To use, uncomment this below line —
          field_rename: snake
